spring.application.name=pravallika-portfolio

# ================= DATABASE =================

spring.datasource.password=${PORTFOLIO_POST_PASSWORD}
spring.datasource.url=${PORTFOLIO_DATABASE_URL}
spring.datasource.username=${PORTFOLIO_DATABASE_USERNAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ================= BREVO =================

brevo.api.key=${PORTFOLIO_BREVO_API_KEY}
brevo.sender.email=${PORTFOLIO_BREVO_SENDER_EMAIL}
brevo.sender.name=${PORTFOLIO_BREVO_SENDER_NAME}


# ================= SERVER =================

server.port=${PORT:8080}